version: '3.2'

services:
  papercups:
    image: papercups-dev
    restart: always
    container_name: papercups
    ports:
      - '3000:3000'
      - '4000:4000'
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && echo 'running' && /entrypoint.sh run"
    depends_on:
      - db
    environment:
      DATABASE_URL: 'ecto://postgres:Eidj7GuSz7bz@db/postgres'
      # PUT YOUR OWN SECRET KEYBASE HERE (MUST BE AT LEAST 64 BYTES)
      SECRET_KEY_BASE: '3g8UCH1EQKVnyzLjmX571FJH9akcxZaHd5X/ek2SW4/H4Dd0zyFDTMAHLYIcYIc4'
      BACKEND_URL: 'localhost'
      MIX_ENV: 'prod'
      REQUIRE_DB_SSL: 'false'
      REACT_APP_FILE_UPLOADS_ENABLED: 1
      # Replace with your domain name
      REACT_APP_URL: 'app.papercups.io'
  db:
    image: postgres:alpine
    restart: always
    container_name: db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: Eidj7GuSz7bz
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
